theme: jekyll-theme-cayman
title: <img src="./assets/images/minic-login.png" alt="minic-login" style="width: 50px;"/>Cocktail minic
description: Experience the Cocktail Cloud
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
