theme: jekyll-theme-cayman
title: Cocktail minic
description: Experience the Cocktail Cloud
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
